import { Cars } from "./type";

export const carsStore: Array<Cars>  = [
  {
    id: 1,
    model: "BMW",
    status: "premium",
    price: 9000000,
    engine_power: 625,
    color: "черный",
    typeCar: "легковая",
    img: "bmw.png",
  },
  {
    id: 2,
    model: "Lada",
    status: "budget",
    price: 1500000,
    engine_power: 163,
    color: "белый",
    typeCar: "легковая",
    img: "lada.png",
  },
  {
    id: 3,
    model: "KAMAZ",
    status: "рабочий",
    price: 15000000,
    engine_power: 1023,
    color: "red",
    typeCar: "грузовая",
    img: "kamaz.png",
  },
  {
    id: 4,
    model: "GAZ",
    status: "рабочий",
    price: 14000000,
    engine_power: 923,
    color: "серый",
    typeCar: "грузовик",
    img: "gaz.png",
  },
  {
    id: 5,
    model: "UAZ",
    status: "рабочий",
    price: 5000000,
    engine_power: 800,
    color: "зеленая",
    typeCar: "легковая",
    img: "uaz.png",
  },
  {
    id: 6,
    model: "MERSEDES",
    status: "PREMIUM",
    price: 9500000,
    engine_power: 630,
    color: "металлик",
    typeCar: "легковая",
    img: "mercedes.png",
  },
  {
    id: 7,
    model: "CHERY",
    status: "budget",
    price: 1500000,
    engine_power: 200,
    color: "голубая",
    typeCar: "легковая",
    img: "chery.png",
  },
];
