import { Cars } from "./type";

export const carsStore: Array<Cars>  = [
  {
    id: 1,
    model: "BMW",
    status: "premium",
    price: 9000000,
    engine_power: 625,
    color: "black",
    typeCar: "passenger",
    img: "bmw.png",
  },
  {
    id: 2,
    model: "Lada",
    status: "budget",
    price: 1500000,
    engine_power: 163,
    color: "white",
    typeCar: "passenger",
    img: "lada.png",
  },
  {
    id: 3,
    model: "KAMAZ",
    status: "work",
    price: 15000000,
    engine_power: 1023,
    color: "red",
    typeCar: "truck",
    img: "kamaz.png",
  },
  {
    id: 4,
    model: "GAZ",
    status: "work",
    price: 14000000,
    engine_power: 923,
    color: "grey",
    typeCar: "truck",
    img: "gaz.png",
  },
  {
    id: 5,
    model: "UAZ",
    status: "work",
    price: 5000000,
    engine_power: 800,
    color: "green",
    typeCar: "passenger",
    img: "uaz.png",
  },
  {
    id: 6,
    model: "MERSEDES",
    status: "PREMIUM",
    price: 9500000,
    engine_power: 630,
    color: "metallic",
    typeCar: "passenger",
    img: "mercedes.png",
  },
  {
    id: 7,
    model: "CHERY",
    status: "budget",
    price: 1500000,
    engine_power: 200,
    color: "blue",
    typeCar: "passenger",
    img: "chery.png",
  },
];
